# TODO tasarım güzelleştirilecek
GET http://localhost:8080/patients/all

###
GET http://localhost:8080/invoices/all

###


GET http://localhost:8080/prescriptions/all


###

GET http://localhost:8080/invoices/all


###

GET http://localhost:8080/doctors/all


###

GET http://localhost:8080/times/all


###

GET  http://localhost:8080/appointments/all